### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by 666dechaoge** [mouyase/pivisionM#19]
登录不了了，api不能用了

**Comment by StarHeartHunt** [comment]
### 补充
这是 pixiv 更改了 `OAuth` 策略导致的，pivisionM做了 `access_token` 与 `refresh_token`的持久化，原先用户不受影响。现已有解决方案(Python)获取 `access_token` 与  `refresh_token`。

参阅[https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362](https://gist.github.com/ZipFile/c9ebedb224406f4f11845ab700124362)
@mouyase

**Comment by kxy09** [comment]
@StarHeartHunt 请问获得两个token后应该如何登录呢？填入账号密码栏无效

**Comment by Hellobaka** [comment]
同问
